# Generated by Django 6.0.6 on 2026-06-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="total_xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
