# Generated by Django 6.0.6 on 2026-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_userprofile_total_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="xp_accuracy_bonus_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="xp_completed_levels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="xp_completion_bonus_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="xp_perfect_run_bonus_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="xp_streak_bonus_awarded_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionattempt",
            name="xp_awarded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
