# Generated by Django 6.0.6 on 2026-06-13 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="pdf", max_length=20)),
                ("topic", models.CharField(default="General", max_length=100)),
                ("score", models.FloatField(default=0.0)),
                ("correct", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100, unique=True)),
                ("mastery_score", models.FloatField(default=0.0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("incorrect_answers", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "topic_mastery",
                "ordering": ["mastery_score", "-last_updated"],
            },
        ),
        migrations.AddField(
            model_name="flashcard",
            name="ease_factor",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="interval_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="last_review_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="next_review_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="repetition_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="memory",
            name="importance_score",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="memory",
            name="learning_progress",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="concepts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="definitions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="relationships",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(0, "Again"), (3, "Hard"), (4, "Good"), (5, "Easy")]
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="chat.flashcard",
                    ),
                ),
            ],
            options={
                "db_table": "review_logs",
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
